// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import FormController from './form_controller'
import LinkController from './link_controller'
import NavbarController from './navbar_controller'

application.register('form', FormController)
application.register('link', LinkController)
application.register('navbar', NavbarController)
