env:
  browser: true
  es2021: true
  jquery: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
globals:
  Turbo: true
  Rails: true
ignorePatterns:
  - app/javascript/vendor
rules:
  import/no-default-export: ['error']
  no-alert: 0
  import/no-named-as-default: 0
  import/prefer-default-export: 0
