endOfLine: lf
printWidth: 100
semi: false
singleQuote: true
trailingComma: all
plugins:
  - '@prettier/plugin-ruby'
  - 'prettier-plugin-tailwindcss'
rubyPlugins: plugin/single_quotes,plugin/trailing_comma
